---
version: 2.0

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-10.3
    steps:
      - checkout
      - run:
          name: Digest
          command: |
            git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            - 1-{{ .Branch }}-{{ checksum "digest" }}
            - 1-{{ .Branch }}-
            - 1-master-
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - save_cache:
          key: 1-{{ .Branch }}-{{ checksum "digest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: make test
      - run:
          name: Lint
          command: make lint
